### ISSUE TITLE
Download CSV

### ISSUE THREAD

**Issue by yajo** [Tardo/OdooTerminal#138]
**Is your feature request related to a problem? Please describe.**
Some times I use OdooTerminal to extract data that otherwise is hard to get. Exporting to JSON helps, but if I need to share that data with functionals, they can't use JSON fine.

**Describe the solution you'd like**
Just like with JSON, I'd love to have a CSV export feature. This would produce a file that's easier to share and use by humans.

**Describe alternatives you've considered**
Converting between both myself.

**Comment by Tardo** [comment]
Done here: https://github.com/Tardo/OdooTerminal/commit/53c58bc6f6cde3b11f5a73b50796c2a4b85a3a19

Would it be useful to support DSV? It is CSV intended for “European” numbers (we use comma instead of period).
Otherwise, in CSV, numbers with commas are enclosed in quotes.

**Comment by yajo** [comment]
I guess it can help, yes.

However, it's true that any user can open any CSV with LibreOffice, Excel or similar and then export it to whatever format they need, in case they need further transformations.

BTW, I notice the changelog for 11.6.1, but I'm unable to get that update. Maybe you forgot to tag the release?

**Comment by Tardo** [comment]
The problem of committing directly to “master” instead of PR hehehe... 11.6.1 not yet released :)

**Comment by Tardo** [comment]
added 'Odoo XML' format too :)
